name: Publish alert

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          ./cowin-vaccine-alerter.sh
          sleep 30
          ./cowin-vaccine-alerter.sh
