name: Publish alert

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run alert script
        run: |
          ./cowin-vaccine-alerter.sh
          sleep 30
          ./cowin-vaccine-alerter.sh
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          COWIN_API_BASE_URL: ${{ secrets.COWIN_API_BASE_URL }}
          COWIN_AUTHORIZATION_TOKEN: ${{ secrets.COWIN_AUTHORIZATION_TOKEN }}
          ORGIN_URL: ${{ secrets.ORGIN_URL }}
          USER_AGENT_HEADER: ${{ secrets.USER_AGENT_HEADER }}
          TELEGRAM_BOT_CHAT_ID: ${{ secrets.TELEGRAM_BOT_CHAT_ID }}
